/** @mainpage LouUI
 *
 * @section introduction Introduction
 *
 * Welcome to LouUI. This is a library designed to make programming a UI on
 * the VEX brain easier. It can be used in combination with the PROS library.
 * This library is only compatible with C++ development, and not C.
 * <br><br>
 * Creating a UI is very useful because it allows for easy autonomous
 * selection and can make debugging easier.
 *
 * @section installation Installation
 *
 * @subsubsection step1 Step 1: PROS Installation
 *
 * This step can be skipped if you already have PROS installed on your computer.
 * <br><br>
 * This library works with LVGL 5.3.1, which has been ported to VEX V5
 * through the PROS library, so PROS must be installed. The installation
 * guides for PROS on Windows, macOS, and Linux can be found on
 * the PROS website
 * <a href="https://pros.cs.purdue.edu/v5/getting-started/index.html">here</a>.
 *
 * @subsubsection step2 Step 2: Create a New PROS Project
 *
 * This step can be skipped if you already have a PROS project that you want
 * to use LouUI with.
 * <br><br>
 * This library only works with a PROS project. With the PROS CLI installed,
 * a new project can be created by running `pros conduct new-project .`
 * in the directory you want the project to be created in.
 *
 * @subsubsection step3 Step 3: Download the Library
 *
 * The library can be downloaded from the releases tab of the
 * <a href="https://github.com/klou23/LouUI">GitHub repo</a>. Both the zip
 * and the tar.gz work.
 *
 * @subsubsection step4 Step 4: Adding the Library
 *
 * LouUI can then be added to any PROS project by moving the `LouUI` folder
 * from the downloaded zip or tar.gz into the `src` directory of the project.
 *
 * @section usage Usage
 *
 * Once included in the PROS project, LouUI can be used just like any other
 * C++ library. Since LouUI does not work with `pros::lcd`, you may have to
 * delete the autogenerated `pros::lcd` code before using LouUI.
 *
 * @subsubsection display Display and Screens
 * The basis of LouUI is a tab-like display system that allows for the
 * creation of multiple different UIs (screens) to be created and allows for
 * the currently displayed screen to be changed using a tab system, similar
 * to a web browser. The first step of building a UI with LouUI is to
 * initialize a Display and add any necessary screens to the display. This is
 * further detailed in documentation for the `Display` class.
 *
 * @subsubsection UIobjects UI Objects
 * LouUI has a set of classes that each represent different UI objects that
 * can be displayed on the brain. These objects can be placed on screens, and
 * in some cases, other objects. Where an object is placed is dependent on
 * the constructor. UI objects also contains a variety of properties that can
 * be edited. Different UI objects have different properties that can be
 * edited. The editable properties, along with the methods to edit the
 * properties, can be found in the documentation for each object.
 *
 * @subsubsection variableDec Variable Declarations
 * LouUI variables need to be persistent. This means that they cannot be
 * local variables that are destroyed after a method is exited. Static
 * variables, class member variables, and global variables all work. However,
 * making all LouUI variables global is recommended because it allows the UI
 * to be dynamically changed during runtime. This is generally done by
 * adding the `extern` keyword before variable declarations.
 *
 * @subsubsection modify Modifying Object Properties
 * Object properties can be modified using the modifier methods. If only one
 * property needs to be modified, the following syntax can be used.
 *
 * @code
 * object->setSize(50, 50);
 * @endcode
 *
 * If multiple object properties need to be set at once, LouUI contains an
 * easy way to do this:
 *
 * @code
 * object = object->setSize(50, 50)
 *                ->setPosition(10, 10)
 *                ->setColor(Color("BLUE"));
 * @endcode
 *
 * @section example Example UI
 *
 * Below is an example of how a simple UI with a button and a label that
 * displays how many times the button has been pressed.
 *
 * @subsubsection variableDeclarations Step 1: Variable Declarations
 * First, the necessary UI objects need to be declared. This can be done by
 * creating a `UIVars.hpp` file. The hpp file will contain the declarations of
 * all of the UI objects. There are 3 UI objects needed for this example: a
 * button, a label that goes in the button, and another label. In addition, a
 * LouUI::Display needs to be declared for every LouUI project. These can all
 * be declared in `UIVars.hpp` as follows:
 *
 * @code
 * extern LouUI::Display display;
 * extern LouUI::Button *button;
 * extern LouUI::Label *buttonLabel;
 * extern LouUI::Label *label;
 * @endcode
 *
 * @subsubsection variableInit Step 2: Variable Initialization
 * After declaring all of the variables, the UI variables need to all be
 * initialized to null, and the Display needs to be initialized using the
 * default constructor. This can be done in a `UIVars.cpp` file as follows:
 *
 * @code
 * #include "UIVars.hpp"
 *
 * LouUI::Display display;
 * LouUI::Button *button = nullptr;
 * LouUI::Label *buttonLabel = nullptr;
 * LouUI::Label *label = nullptr;
 * @endcode
 *
 * @subsubsection buildUI Step 3: Build UI
 *
 * After the UI variables are declared and initialized, the UI variables can be
 * used to build the UI in the PROS `initialize` method. First, a screen needs
 * to be added to the display:
 *
 * @code
 * display.addScreen("Example LouUI Screen");
 * @endcode
 *
 * Then the button and label can be added to the screen:
 *
 * @code
 * button = (new LouUI::Button(display.getScreen("Example LouUI Screen")))
 *         ->setSize(150, 50)
 *         ->align(display.getScreen("Example LouUI Screen"), LouUI::IN_TOP_MID);
 * label = (new LouUI::Label(display.getScreen("Example LouUI Screen")))
 *         ->setText("Counter: 0")
 *         ->align(button->getObj(), LouUI::OUT_BOTTOM_MID, 0, 15);
 * @endcode
 *
 * A label can then be added to the button:
 *
 * @code
 * buttonLabel = (new LouUI::Label(button->getObj()))
 *         ->setText("Click Me!");
 * @endcode
 *
 * @subsubsection addCounter Step 4: Add Counter
 *
 * Once the UI is created, the counter can be implemented. The first step is to
 * add a variable to track how many times the button has been pressed. This can
 * be done by declaring a global variable:
 *
 * @code
 * extern int counter;
 * @endcode
 *
 * Then initializing the variable with value zero:
 *
 * @code
 * int counter = 0;
 * @endcode
 *
 * Next, a `UIFuncs.hpp` file can be created for all functions that are to be
 * called by the UI. Within this file, a function to update the counter and the
 * label can be created:
 *
 * @code
 * lv_res_t incrementCounter(lv_obj_t *obj){
 *     counter++;
 *     label->setText("Counter: " + std::to_string(counter));
 *     return LV_RES_OK;
 * }
 * @endcode
 *
 * This function can then be set as the action to run when the button is
 * pressed in the `initialize` method:
 *
 * @code
 * button->setAction(incrementCounter);
 * @endcode
 *
 * @subsubsection running Step 5: Running Project
 *
 * The project can be run just like any other PROS project (i.e. `pros mu`).
 *
 * Complete source code for this example UI can also be found
 * <a href = "https://github.com/klou23/LouUICounterExample">here</a>.
 */
